Weather/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from weather_app import views
from weather_app.api import SubscriptionViewSet, SubscriptionRetrieveUpdateDestroyView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Your API",
        default_version='v1',
        description="Your API description",
        terms_of_service="https://www.yourapp.com/terms/",
        contact=openapi.Contact(email="contact@yourapp.com"),
        license=openapi.License(name="Your License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api_get_weather/', views.api_get_weather, name='api_get_weather_for_subscribed_cities'),
    path('get-weather/', views.get_weather, name='get_weather'),
    path('api/get-weather/<str:city_name>/', views.get_weather, name='get_weather_by_city'),
    path('api/', include('weather_app.urls')),
    path('registration/', views.register, name='registration'),
    path('login/', views.user_login, name='login'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('logout/', views.logout_view, name='logout'),
    re_path(r'^webpush/', include('webpush.urls')),
    path('api/subscriptions/', SubscriptionViewSet.as_view({'get': 'list', 'post': 'create'}), name='subscription-list-create-api'),
    path('api/subscriptions/<int:pk>/', SubscriptionRetrieveUpdateDestroyView.as_view(), name='subscription-retrieve-update-destroy-api'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

weather_app/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views import UserRegistrationView, subscribe, edit_subscription, delete_subscription, subscription_list


urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('subscribe/', subscribe, name='subscribe'),
    path('edit-subscription/<int:subscription_id>/', edit_subscription, name='edit_subscription'),
    path('delete-subscription/<int:subscription_id>/', delete_subscription, name='delete_subscription'),
    path('subscription-list/', subscription_list, name='subscription_list'),
]

weather_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class User(AbstractUser):
    jwt_token = models.CharField(max_length=255, blank=True, null=True)
    webhook_url = models.URLField(blank=True, null=True)

    class Meta:
        swappable = 'AUTH_USER_MODEL'


class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    city = models.TextField()
    period_choices = [
        ('1', '1 hour'),
        ('3', '3 hours'),
        ('6', '6 hours'),
        ('12', '12 hours'),
    ]
    period = models.CharField(max_length=2, choices=period_choices)
    method_choices = [
        ('email', 'Email'),
        ('push', 'Push Notification'),
        ('webhook', 'Webhook'),
    ]
    method = models.CharField(max_length=10, choices=method_choices)
    last_notification_time = models.DateTimeField(null=True, blank=True)


class City(models.Model):
    name = models.CharField(max_length=255)


class WeatherData(models.Model):
    city = models.ForeignKey('City', on_delete=models.CASCADE)
    temperature = models.FloatField()
    humidity = models.FloatField(null=True)
    timestamp = models.DateTimeField(auto_now_add=True)


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notifications')
    city = models.ForeignKey('City', on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.content}"


class DefaultCity(models.Model):
    name = models.CharField(max_length=255)

weather_app/forms.py
from django import forms
from .models import Subscription
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password


class CitySearchForm(forms.Form):
    search_query = forms.CharField(label='Search for a city', max_length=100)


class SubscriptionForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = ['city', 'period', 'method']


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'A user with the username {username} already exists.')
        return username

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        try:
            validate_password(password1)
        except ValidationError as e:
            raise forms.ValidationError('\n'.join(e.messages))

        return password1

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(f'A user with the email {email} already exists.')
        return email

weather_app/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render

import os
from django.shortcuts import render, redirect, get_object_or_404, reverse
from .models import City, WeatherData, DefaultCity, User
from .forms import CitySearchForm
import requests
import csv
from rest_framework import generics, permissions
from rest_framework.response import Response
from rest_framework_simplejwt.tokens import RefreshToken
from .serializers.serializers import UserSerializer, SubscriptionSerializer
from django.contrib.auth.decorators import login_required
from .models import Subscription
from .forms import SubscriptionForm, RegistrationForm
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate
from django.utils import timezone
from django.contrib.auth import logout
from weather_app.tasks import send_notifications, send_notifications
from .models import Notification
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
import json
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from .api import SubscriptionViewSet, UserRegistrationView
from .utils import get_weather_for_city


def perform_search_in_csv(search_query):
    found_cities = []
    csv_file_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'cities_20000.csv'))

    with open(csv_file_path, 'r') as csvfile:
        csv_reader = csv.reader(csvfile)
        next(csv_reader)
        for row in csv_reader:
            if search_query.lower() in row[1].lower():
                found_cities.append({
                    'city_id': row[0],
                    'city_name': row[1],
                    'state_code': row[2],
                    'country_code': row[3],
                    'country_full': row[4],
                    'lat': row[5],
                    'lon': row[6],
                })
    return found_cities


def get_weather(request, city_name='Kiev'):
    form = CitySearchForm(request.GET)
    found_cities = []
    temperature = None

    if form.is_valid():
        search_query = form.cleaned_data['search_query']
        found_cities = perform_search_in_csv(search_query)

        if len(found_cities) == 1:
            city_name = found_cities[0]['city_name']
            url = f'https://api.weatherbit.io/v2.0/current?city={city_name}&key={os.environ.get("WEATHER_API_KEY")}'
            response = requests.get(url)
            data = response.json()
            temperature = data['data'][0]['temp']

    default_cities = DefaultCity.objects.all()

    context = {'temperature': temperature, 'city': city_name, 'default_cities': default_cities, 'form': form,
               'found_cities': found_cities}
    return render(request, 'weather.html', context)


@login_required
def subscribe(request):
    if request.method == 'POST':
        form = SubscriptionForm(request.POST)
        if form.is_valid():
            subscription = form.save(commit=False)
            subscription.user = request.user
            subscription.save()
            return redirect('subscription_list')
    else:
        form = SubscriptionForm()

    return render(request, 'subscribe.html', {'form': form})


@login_required
def edit_subscription(request, subscription_id):
    subscription = get_object_or_404(Subscription, id=subscription_id, user=request.user)

    if request.method == 'POST':
        form = SubscriptionForm(request.POST, instance=subscription)
        if form.is_valid():
            form.save()
            return redirect('subscription_list')
    else:
        form = SubscriptionForm(instance=subscription)

    return render(request, 'edit_subscription.html', {'form': form, 'subscription': subscription})


@login_required
def delete_subscription(request, subscription_id):
    subscription = get_object_or_404(Subscription, id=subscription_id, user=request.user)
    subscription.delete()
    return redirect('subscription_list')


@login_required
def subscription_list(request):
    subscriptions = Subscription.objects.filter(user=request.user)
    return render(request, 'subscription_list.html', {'subscriptions': subscriptions})


@api_view(['GET'])
def subscription_list_api(request):
    subscriptions = Subscription.objects.filter(user=request.user)
    serializer = SubscriptionSerializer(subscriptions, many=True)
    return Response(serializer.data)


def user_login(request):
    if request.user.is_authenticated:
        messages.success(request, 'Ви вже увійшли до системи.')
        return redirect('')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('')
            else:
                messages.error(request, 'Неправильний логін чи пароль.')
    else:
        form = AuthenticationForm()

    context = {
        'form': form,
    }
    return render(request, 'login.html', context)


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.last_login = timezone.now()
            user.save()
            login(request, user)
            return HttpResponseRedirect(reverse('profile', args=[user.username]))
    else:
        form = RegistrationForm()

    return render(request, 'registration.html', {'form': form})


@login_required
def logout_view(request):
    logout(request)
    return redirect('login')


def show_notifications(request):
    notifications = Notification.objects.all()
    return render(request, 'weather.html', {'notifications': notifications})


def api_get_weather(request):
    search_query = request.GET.get('search_query', '')
    found_cities = perform_search_in_csv(search_query)

    if found_cities:
        city_name = found_cities[0]['city_name']
        url = f'https://api.weatherbit.io/v2.0/current?city={city_name}&key={os.environ.get("WEATHER_API_KEY")}'
        response = requests.get(url)
        weather_data = response.json()

        if 'data' in weather_data and weather_data['data']:
            temperature = weather_data['data'][0]['temp']
            return JsonResponse({'temperature': temperature, 'city': city_name})
        else:
            return JsonResponse({'error': 'Weather data not found for the city'})
    else:
        return JsonResponse({'error': 'City not found'})


@csrf_exempt
def webhook_receiver(request, user_id):
    if request.method == 'POST':
        user = get_object_or_404(User, id=user_id)

        try:
            data = json.loads(request.body.decode('utf-8'))

            city_name = data.get('city')
            city = get_object_or_404(City, name=city_name)

            notification = Notification.objects.create(
                user=user,
                city=city,
                content=data.get('content'),
            )

            return JsonResponse({'status': 'success', 'notification_id': notification.id})
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)}, status=500)
        else:
            return JsonResponse({'status': 'error', 'message': 'Method Not Allowed'}, status=405)

weather_app/templates/base.html
{% load static webpush_notifications %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Weather{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">

    {% block extra_head %}{% endblock %}
    {% webpush_header %}
</head>
<body>
    {% load webpush_notifications %}
    {% webpush_header %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'get_weather' %}">
                                Weather
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'subscription_list' %}">
                                Підписки
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">
                                Вийти
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">
                                Увійти
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'registration' %}">
                                Реєстрація
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>


    <div class="center-buttons">
        {% webpush_button %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-pzjw8j+ua/CeKXi5oGMLcAqJ1dbRU5d/oo8LdXEnz9t0z2ZbXlCTY5uFZB9K9VIW" crossorigin="anonymous"></script>
    <script src="{% static 'webpack_bundles/main.js' %}"></script>
</body>
</html>

weather_app/templates/edit_subscription.html
{% extends 'base.html' %}

{% block content %}
    <h2>Edit Subscription</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
{% endblock %}

weather_app/templates/login.html
{% extends 'base.html'%}

{% block title %}
    Login
{% endblock %}

{% block content %}
    <div class="center-container">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <form action="{% url 'login' %}" method="post" class="center-form">
            {% csrf_token %}

            {{ form.as_p }}

            <input type="submit" value="Login" class="button">

            <a href="{% url 'social:begin' 'google-oauth2' %}" class="social-button google-button">Войти через Google</a>
            <a href="{% url 'social:begin' 'github' %}" class="social-button github-button">Войти через GitHub</a>
        </form>

    </div>
{% endblock %}

weather_app/templates/registration.html
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Registration</title>#}
{#</head>#}
{#<body>#}
{#    <h2>Registration</h2>#}
{#    <form method="post" action="{% url 'registration' %}" enctype="multipart/form-data">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit">Register</button>#}
{#    </form>#}
{#</body>#}
{#</html>#}


{% extends 'base.html' %}

{% block title %}
    Registration
{% endblock %}

{% block content %}
    <div class="center-container">
        <form method="post" action="{% url 'registration' %}" enctype="multipart/form-data" class="center-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="button">Register</button >
        </form>
    </div>
    <div class="center-container">
        <form method="post" action="{% url 'registration' %}" enctype="multipart/form-data" class="center-form">
    <a href="{% url 'social:begin' 'google-oauth2' %}" class="social-button google-button">Войти через Google</a>
    <a href="{% url 'social:begin' 'github' %}" class="social-button github-button">Войти через GitHub</a>
        </form>
    </div>
{% endblock %}

weather_app/templates/subscribe.html
{% extends 'base.html' %}

{% block content %}
    <h2>Subscribe to a City</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Subscribe</button>
    </form>
{% endblock %}

weather_app/templates/subscription_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h2>Your Subscriptions</h2>
    <ul>
        {% for subscription in subscriptions %}
            <li>
                {{ subscription.city }} ({{ subscription.get_period_display }}) - {{ subscription.get_method_display }}
                <a href="{% url 'edit_subscription' subscription.id %}">Edit</a>
                <a href="{% url 'delete_subscription' subscription.id %}">Delete</a>
            </li>
        {% endfor %}

        <hr> {# розділяюча полоса#}

        <ul>
        {% for subscription in subscriptions %}
            <li id="{{ subscription.city }}">
                {{ subscription.city }} - <span class="temperature">Завантаження...</span>
            </li>
        {% endfor %}
        </ul>

        <script>
        document.addEventListener('DOMContentLoaded', function() {
            document.querySelectorAll('ul li').forEach(function(listItem) {
                const city = listItem.id;
                fetch(`/api_get_weather/?search_query=${city}`, {
                    method: 'GET',
                })
                .then(response => response.json())
                .then(data => {
                    const temperatureElement = listItem.querySelector('.temperature');
                    if ('temperature' in data) {
                        temperatureElement.innerText = `Температура: ${data.temperature}°C`;
                    } else {
                        temperatureElement.innerText = `Помилка: ${data.error}`;
                    }
                })
                .catch(error => {
                    console.error(`Помилка під час виконання запиту для міста ${city}:`, error);
                });
            });
        });
        </script>
    </ul>
{% endblock %}

weather_app/templates/weather.html
{% extends 'base.html' %}

{% block title %}Select a City - Weather{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <h2>Select a City:</h2>

            <div class="card">

                <form method="get" action="{% url 'get_weather' %}">
                    {{ form }}
                    <button type="submit">Search</button>
                </form>

                {% if found_cities %}
                    {% if found_cities|length == 1 %}
                        <h2>Current Temperature in {{ city }}:</h2>
                        <p>{{ temperature }} °C</p>

                        <form method="post" action="{% url 'subscribe' %}">
                            {% csrf_token %}
                            <input type="hidden" name="city" value="{{ city }}">
                            <label for="period">Select Notification Period:</label>
                            <select name="period">
                                <option value="1">1 hour</option>
                                <option value="3">3 hours</option>
                                <option value="6">6 hours</option>
                                <option value="12">12 hours</option>
                            </select>
                            <label for="method">Select Notification Method:</label>
                            <select name="method">
                                <option value="email">Email</option>
                                <option value="push">Push Notification</option>
                                <option value="webhook">Webhook</option>
                            </select>
                            <button type="submit">Subscribe</button>
                        </form>

                    {% else %}
                        <h2>Search Results:</h2>
                        <ul>
                            {% for city_info in found_cities %}
                                <li><a href="{% url 'get_weather' %}?search_query={{ city_info.city_name }}">{{ city_info.city_name }} ({{ city_info.country_code }})</a></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                {% elif temperature %}
                    <h2>Current Temperature in {{ city }}:</h2>
                    <p>{{ temperature }} °C</p>

                    <form method="post" action="{% url 'subscribe' %}">
                        {% csrf_token %}
                        <input type="hidden" name="city" value="{{ city }}">
                        <label for="period">Select Notification Period:</label>
                        <select name="period">
                            <option value="1">1 hour</option>
                            <option value="3">3 hours</option>
                            <option value="6">6 hours</option>
                            <option value="12">12 hours</option>
                        </select>
                        <label for="method">Select Notification Method:</label>
                        <select name="method">
                            <option value="email">Email</option>
                            <option value="push">Push Notification</option>
                            <option value="webhook">Webhook</option>
                        </select>
                        <button type="submit">Subscribe</button>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}